### ISSUE TITLE
Panic during reconnect to mulfunctional Redis Cluster

### ISSUE THREAD

**Issue by FZambia** [rueian/rueidis#55] opened 2022-06-21 08:27 UTC
Got the panic like this after reconnect to a Redis Cluster:

```
panic: protocol bug, message handled out of order

goroutine 1148 [running]:
github.com/rueian/rueidis.(*pipe)._backgroundRead(0xc0014ae210)
  /Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.57/pipe.go:301 +0x725
github.com/rueian/rueidis.(*pipe)._background(0xc0014ae210)
  /Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.57/pipe.go:135 +0x185
created by github.com/rueian/rueidis.(*pipe).background.func1
  /Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.57/pipe.go:113 +0x5a
exit status 2
```

In my case I had a working Redis cluster, then stopped the cluster (I am using docker-compose from https://github.com/Grokzen/docker-redis-cluster), ran it again. Newly created cluster was not properly functional due to cluster setup error, so every operation on every node at this point returned:

```
127.0.0.1:7005> set x 1
(error) CLUSTERDOWN Hash slot not served
```

I'll try to provide a minimal reproducer example soon. This may be a bit tricky to reproduce though.

**Comment by rueian** [comment] 2022-06-21 09:16
Oh, I might know the reason of this. This could also take me a couple of days.

**Comment by FZambia** [comment] 2022-06-24 08:08
I was trying to reproduce the panic, but can not now. Maybe I changed the code somehow to avoid it to happen. Were you able to reproduce it btw?

One more thing though is that program like this:

```go
func run() {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:7000", "127.0.0.1:7001"},
	})
	if err != nil {
		panic(err)
	}
	defer client.Close()

	for {
		log.Println("start pub/sub")
		conn, _ := client.Dedicate()
		wait := conn.SetPubSubHooks(rueidis.PubSubHooks{
			OnMessage: func(m rueidis.PubSubMessage) {

			},
		})
		log.Println("pub/sub is ready")
		err := <-wait
		log.Println("pub/sub error", err)
		conn.Close()
		time.Sleep(1 * time.Millisecond)
	}
}
```

Does not detect cluster shutdowns - i.e. with single Redis instance PUB/SUB interrupted on Redis close and goes to reconnect loop, but with Redis Cluster shutting down the cluster does not result into PUB/SUB connection close.

**Comment by rueian** [comment] 2022-06-24 08:36
Hi @FZambia,

For the dedicated cluster client, the underlying connection is actually not established until you send a command.  Because which node to connect to is decided by the key slot of the command.

That is why the above program has no reaction to cluster shutdown, since the underlying connection is not yes established after all.

**Comment by FZambia** [comment] 2022-06-24 08:55
I see, makes sense!

**Comment by FZambia** [comment] 2022-06-24 10:40
Think I was able to reproduce a panic by moving Cluster slot to another node.

It's reproduced with https://github.com/rueian/rueidis/pull/56/commits/2eba08d064f35fd4275d17bd60c09eb167f39034

**Comment by FZambia** [comment] 2022-06-24 10:59
So steps to reproduce.

1. Run Redis Cluster
2. Run program like this:

```
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/rueian/rueidis"
)

func main() {
	run()
}

func run() {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:7000", "127.0.0.1:7001"},
	})
	if err != nil {
		panic(err)
	}
	defer client.Close()

	for {
		log.Println("start pub/sub")
		conn, _ := client.Dedicate()
		wait := conn.SetPubSubHooks(rueidis.PubSubHooks{
			OnMessage: func(m rueidis.PubSubMessage) {

			},
			OnSubscription: func(s rueidis.PubSubSubscription) {
				fmt.Println(s.Kind, s.Channel)
			},
		})
		log.Println("pub/sub is ready")
		conn.Do(context.Background(), conn.B().Ssubscribe().Channel("test").Build())
		err := <-wait
		log.Println("pub/sub error", err)
		conn.Close()
		time.Sleep(1 * time.Millisecond)
	}
}
```
3. Migrate slot from one cluster node to another:

```
redis-cli -p 7001
127.0.0.1:7001> cluster nodes
01b094549dcda3ffc26a09ad24b9b47b817986f9 127.0.0.1:7005@17005 slave 5c15c1758732ad5dd6208ae65a24b694a215f385 0 1656068049529 3 connected
5c15c1758732ad5dd6208ae65a24b694a215f385 127.0.0.1:7002@17002 master - 0 1656068049000 3 connected 10923-16383
6c95c902602fdfb2251ec7631b6b0d590bcd4111 127.0.0.1:7004@17004 slave 8d075329d148e201e4ecb48d8317dece5e304745 0 1656068049940 8 connected
cce502301ce3bb3421b5a7b611df84f51d9c220d 127.0.0.1:7000@17000 master - 0 1656068048912 9 connected 0-5460 5649 6918
d322a8b4aba02949c34104886a169523662bfb75 127.0.0.1:7003@17003 slave cce502301ce3bb3421b5a7b611df84f51d9c220d 0 1656068049530 9 connected
8d075329d148e201e4ecb48d8317dece5e304745 127.0.0.1:7001@17001 myself,master - 0 1656068048000 8 connected 5461-5648 5650-6917 6919-10922 [5649->-cce502301ce3bb3421b5a7b611df84f51d9c220d] [6918->-cce502301ce3bb3421b5a7b611df84f51d9c220d]
```

On Node 7000:

```
127.0.0.1:7000> CLUSTER SETSLOT 6918 IMPORTING 8d075329d148e201e4ecb48d8317dece5e304745
OK
```

On Node 7001:

```
127.0.0.1:7001> CLUSTER SETSLOT 6918 MIGRATING cce502301ce3bb3421b5a7b611df84f51d9c220d
```

On Node 7000:

```
127.0.0.1:7000> CLUSTER SETSLOT 6918 NODE cce502301ce3bb3421b5a7b611df84f51d9c220d
OK
```

At this moment panic happens:

```
2022/06/24 13:49:50 pub/sub is ready
ssubscribe test
sunsubscribe test
panic: protocol bug, message handled out of order

goroutine 22 [running]:
github.com/rueian/rueidis.(*pipe)._backgroundRead(0xc0000f0210)
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.59-0.20220623171244-2eba08d064f3/pipe.go:295 +0x865
github.com/rueian/rueidis.(*pipe)._background(0xc0000f0210)
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.59-0.20220623171244-2eba08d064f3/pipe.go:137 +0x172
created by github.com/rueian/rueidis.(*pipe).background.func1
	/Users/fz/go/pkg/mod/github.com/rueian/rueidis@v0.0.59-0.20220623171244-2eba08d064f3/pipe.go:115 +0x5a
exit status 2
```

**Comment by rueian** [comment] 2022-06-24 13:15
Oh, thank you very much.

Redis sends a `sunsubscribe` message right after the `CLUSTER SETSLOT 6918 NODE cce502301ce3bb3421b5a7b611df84f51d9c220d`. I need to find a way to deal with it.

**Comment by rueian** [comment] 2022-06-25 06:46
Hi @FZambia,

The above issues are fixed in the latest commit of PR https://github.com/rueian/rueidis/pull/56:
* Failures of `subscribe/unsubscribe` are not handled previously and cause panic with "protocol bug". This is the `CLUSTERDOWN` case you mentioned. 
* `sunsubscribe` messages send by redis proactively are not handled previously. This is the `CLUSTER SETSLOT` case you reproduced.

**Comment by FZambia** [comment] 2022-06-25 09:36
Just checked – no panic, thanks! 🎉 

Though one last thing – after migrating a slot I am successfully getting `sunsubscribe` and trying to restart PUB/SUB for a slot (since it's migrated – I need to re-subscribe from scratch). But reconnect/resubscribe loop constantly receives an error:

```
MOVED 5649 127.0.0.1:7000
``` 

Seems like information about slots is not updated in rueidis cache? Or slot refresh not triggered? If I restart my app – then all subscriptions are established correctly, picking correct node for slot subscribe.

**Comment by rueian** [comment] 2022-06-25 14:53
Hi @FZambia,

Yes, you are right. I had missed triggering slot refresh in the dedicated client. I have reworked that in the latest commit.

Now it should work with the following program:

```golang
package main

import (
	"context"
	"fmt"

	"github.com/rueian/rueidis"
)

func main() {
	client, err := rueidis.NewClient(rueidis.ClientOption{
		InitAddress: []string{"127.0.0.1:7000", "127.0.0.1:7001"},
	})
	if err != nil {
		panic(err)
	}
	defer client.Close()

	for {
		conn, _ := client.Dedicate()
		sig := make(chan struct{})
		conn.SetPubSubHooks(rueidis.PubSubHooks{
			OnMessage: func(m rueidis.PubSubMessage) {
				fmt.Println(m)
			},
			OnSubscription: func(s rueidis.PubSubSubscription) {
				fmt.Println(s)
				if s.Kind == "sunsubscribe" {
					close(sig)
				}
			},
		})
		if err := conn.Do(context.Background(), conn.B().Ssubscribe().Channel("test").Build()).Error(); err == nil {
			<-sig
		}
		conn.Close()
	}
}
```

Note that the `MOVED` error will be returned from the `conn.Do()` and the dedicated client will not switch to the new redis node automatically. You need to go through `conn, _ := client.Dedicate()` again to switch to the correct redis node.

I have tried to implement handling `MOVED` error transparently in dedicated client but failed. It is mainly because it is quite hard to make the channel returned from `conn.SetPubSubHooks()` decoupled from the underlying connection.

**Comment by FZambia** [comment] 2022-06-25 15:29
>  the dedicated client will not switch to the new redis node automatically. You need to go through conn, _ := client.Dedicate() again to switch to the correct Redis node.

Yep, I already do this with Dedicated connection, I think re-establishing is pretty reasonable in this case, should not happen often.

Actually I'd prefer Redis to close PUB/SUB connection automatically upon slot migration, possibly with an error containing where slot was moved to instead of sending `sunsubscribe`. Given at most once nature of PUB/SUB connection I am a bit worried that `sunsubscribe` can be lost in some cases. And also connection will receive `sunsubscribe` for all the channels in slot - sth I don't really need. Closing from Redis side seems much more attractive. Maybe I'll try to address this in Redis repo a bit later.

I just tried the latest commit – and everything works as expected. Such a great progress, many thanks – will continue experimenting, the feeling is that it's very close :) Also want to test Sentinel scenario - seems the last part of the migration.

**Comment by rueian** [comment] 2022-06-26 02:46
Hi @FZambia,

> I just tried the latest commit – and everything works as expected. Such a great progress, many thanks – will continue experimenting, the feeling is that it's very close :) Also want to test Sentinel scenario - seems the last part of the migration.

Thank you for your assistance, v0.0.59 is released. Please let me know if you find any issues. I am happy to help.

> Actually I'd prefer Redis to close PUB/SUB connection automatically upon slot migration, possibly with an error containing where slot was moved to instead of sending `sunsubscribe`

Agreed. `sunsubscribe` message is the only special case currently that does not fit well into the request<->response communication model: It may or may not be an `out of band` message. This makes the client hard to handle. 

It seems that they had discussed just closing the connection from the Redis side once the slot was moved: https://github.com/redis/redis/pull/8621#issuecomment-922069361, but it just not happened finally. And I didn't find further discussion on this.

**Closed** 2022-06-26 05:42 UTC

**Comment by verejoel** [comment] 2023-01-28 13:18
I ran into this problem again using the client in Thanos. The panic was preceded by many exceeded context deadlines.
```
level=warn ts=2023-01-27T20:40:57.861170828Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861231427Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861180428Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861237527Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861248327Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861216228Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861274627Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861305927Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861302627Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
level=warn ts=2023-01-27T20:40:57.861303927Z caller=redis_client.go:289 msg="failed to mget items from redis" err="context deadline exceeded" items=0
panic: protocol bug, message handled out of order

goroutine 964911 [running]:
github.com/rueian/rueidis.(*pipe)._backgroundRead(0xc003877560)
	/go/pkg/mod/github.com/rueian/rueidis@v0.0.88/pipe.go:414 +0x8ff
github.com/rueian/rueidis.(*pipe)._background(0xc003877560)
	/go/pkg/mod/github.com/rueian/rueidis@v0.0.88/pipe.go:226 +0x7e
created by github.com/rueian/rueidis.(*pipe).background.func1
	/go/pkg/mod/github.com/rueian/rueidis@v0.0.88/pipe.go:210 +0x5a
```

**Comment by rueian** [comment] 2023-01-28 13:44
Hi @verejoel, thanks for the report. I will try to figure it out. Do you have any other clue that could help reproduce the problem?

**Comment by verejoel** [comment] 2023-01-28 13:51
We're using Azure Cache for Redis, Standard tier 26 GB (C5 instance). I just checked and the Redis version is 4, not the latest 6. On Monday I will ask our team to upgrade to 6 to see if this might resolve the issue.

Thanos version is the latest release (v0.30.1) and I'm using their default connection settings for the redis client with TLS enabled, as documented [here](https://thanos.io/v0.30/components/store.md/#redis-index-cache).

**Comment by rueian** [comment] 2023-02-01 16:11
Hi @verejoel,

The bug should be fixed by https://github.com/rueian/rueidis/pull/170. I will later open a PR to Thanos for updating rueidis as well.

This bug won't be triggered if you have client-side caching enabled with Redis >= 6. So, if you can't wait for a new Thanos release, upgrading your Redis should also work around the problem.
